### PR TITLE
7 [clickHandler makes popup] and 9 [fix bounds on map]

### LINKED ISSUE #7: Make all stations clickable

### LINKED ISSUE #9: User should be able to zoom in on all parts of the map -- not just the center

### PR DESCRIPTION
**Pull request by lemkey**
Closes #7 - clickHandler makes popup on stations
Resolves #9  - fix bounds on map

### CODE REVIEW

File: src/pages/index.js [hunk 1]
```diff
@@ -92,9 +92,9 @@ const MapEffect = ({ markerRef }) => {
 const ConfigureMap = () => {
   const L = useMap()
 
-  React.useEffect(() => {
-    L.setMaxBounds(L.getBounds())
-  }, [L])
+  // React.useEffect(() => {
```
Comment (gynnantonix) [inline src/pages/index.js:95]: Please delete commented-out lines

**Review by gynnantonix — CHANGES_REQUESTED** [review]
